pipeline {
  agent none

  stages {
    agent any
    stage('prep') {
      script{
        checkout scm
      }
      steps {
        sh 'if [ ! -d /var/jenkins_home/.gradle ];then \
         mkdir -p /var/jenkins_home/.gradle; \
         fi;'
      }
    }
    stage('test') {
      agent {
        docker {
          image 'gradle:jdk8'
          args  '-v ${env.HOME}/.gradle:/home/gradle/.gradle'
        }
        steps {
          sh 'cd complete && ./gradlew test'
        }

      }
    }
    stage('Build') {
      agent {
        docker {
          image 'gradle:jdk8'
          args  '-v ${env.HOME}/.gradle:/home/gradle/.gradle'
        }
      steps {
        sh 'cd complete && ./gradlew test'
      }
    }
  }
 }
}
