pipeline {
  agent none

  stages {
    stage('prep') {
      agent {
        label 'master'
      }
      steps {
        checkout scm
      }

    }
    // checking the directory
    stage('check') {
      agent {
        label 'master'
      }
      steps {
        sh '''
        if [ ! -d ${HOME}/.gradle ];then
         mkdir -p ${HOME}/.gradle
         elif [ `ls -ld /var/jenkins_home/.gradle/ | awk '{print $3}'` != "ubuntu" ];then
         chown 1000:1000 ${HOME}/.gradle
         else
         echo "Directory is configured!!"
         fi
         '''
      }
    }
    // test the java app inside the docker container with gradle script
    stage('test') {
      agent {
        docker {
          image 'gradle:jdk8'
          args  '-v ${env.HOME}/.gradle:/home/gradle/.gradle'
        }
        steps {
          sh 'cd complete && ./gradlew test'
        }

      }
    }
    // build the java app within the same
    stage('Build') {
      agent {
        docker {
          image 'gradle:jdk8'
          args  '-v ${env.HOME}/.gradle:/home/gradle/.gradle'
        }
      steps {
        sh 'cd complete && ./gradlew run'
      }
    }
    // email to me when build stage has completed successfully
    post {
      success {
        emailext(
          subject: "${env.JOB_NAME} [${env.BUILD_NUMBER}] has completed successfully",
          body: """<p>'${env.JOB_NAME} [${env.BUILD_NUMBER}]' completed":</p>
          <p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>
          ${JELLY_SCRIPT,template="html"}""",
          to: "fisherhuang1986@gmail.com"
        )
      }
    }
  }
 }
}
