/var/jenkins_homepipeline {
  agent none

  stages {
    stage('Prep') {
      agent {
        label 'master'
      }
      steps {
        checkout scm
      }

    }
    // checking the directory
    stage('Check') {
      agent {
        label 'master'
      }
      steps {
        sh '''
        if [ ! -d /var/jenkins_home/.gradle ];then
         mkdir -p /var/jenkins_home/.gradle
         elif [ `ls -ld ${HOME}/.gradle/ | awk '{print $3}'` != "ubuntu" ];then
         chown 1000:1000 ${HOME}/.gradle
         else
         echo "Directory is configured!!"
         fi
         '''
      }
    }
    // test the java app inside the docker container with gradle script
    stage('Test') {
      agent {
        docker {
          image 'gradle:jdk8'
          args  '-v /var/jenkins_home/.gradle:/home/gradle/.gradle'
        }
      }
        steps {
          sh 'cd complete && ./gradlew test'
        }
    }
    // build the java app within the same
    stage('Build') {
      agent {
        docker {
          image 'gradle:jdk8'
          args  '-v /var/jenkins_home/.gradle:/home/gradle/.gradle'
        }
      }
      steps {
        sh 'cd complete && ./gradlew run'
      }
      // email to me when build stage has completed successfully
      post {
        success {
          emailext(
            subject: "${env.JOB_NAME} [${env.BUILD_NUMBER}] has completed successfully",
            body: '${JELLY_SCRIPT,template="html"}',
            to: "fisherhuang1986@gmail.com"
          )
        }
      }
    }
  }
}
